export const STATICART_ERROR_CODES = {
  STATICART_VALIDATION_ERROR: "STATICART_VALIDATION_ERROR",
  STATICART_INVALID_ENUM: "STATICART_INVALID_ENUM",
  STATICART_REQUIRED_FIELD_MISSING: "STATICART_REQUIRED_FIELD_MISSING",
  STATICART_INVALID_CURSOR: "STATICART_INVALID_CURSOR",

  STATICART_UNAUTHORIZED: "STATICART_UNAUTHORIZED",
  STATICART_FORBIDDEN: "STATICART_FORBIDDEN",
  STATICART_ROLE_NOT_ALLOWED: "STATICART_ROLE_NOT_ALLOWED",
  STATICART_ASSET_NOT_OWNED_BY_ACTOR: "STATICART_ASSET_NOT_OWNED_BY_ACTOR",

  STATICART_ASSET_NOT_FOUND: "STATICART_ASSET_NOT_FOUND",
  STATICART_FILE_NOT_FOUND: "STATICART_FILE_NOT_FOUND",
  STATICART_REVIEW_REQUEST_NOT_FOUND: "STATICART_REVIEW_REQUEST_NOT_FOUND",
  STATICART_ASSET_STATE_CONFLICT: "STATICART_ASSET_STATE_CONFLICT",
  STATICART_REVIEW_ALREADY_PENDING: "STATICART_REVIEW_ALREADY_PENDING",
  STATICART_VERSION_CONFLICT: "STATICART_VERSION_CONFLICT",
  STATICART_IDEMPOTENCY_REPLAY_MISMATCH: "STATICART_IDEMPOTENCY_REPLAY_MISMATCH",

  STATICART_REVIEW_SUBMISSION_PRECONDITION_FAILED: "STATICART_REVIEW_SUBMISSION_PRECONDITION_FAILED",
  STATICART_PUBLISH_PRECONDITION_FAILED: "STATICART_PUBLISH_PRECONDITION_FAILED",
  STATICART_RIGHTS_POLICY_BLOCKED: "STATICART_RIGHTS_POLICY_BLOCKED",
  STATICART_REGION_POLICY_BLOCKED: "STATICART_REGION_POLICY_BLOCKED",
  STATICART_AGE_POLICY_BLOCKED: "STATICART_AGE_POLICY_BLOCKED",
  STATICART_EXHIBITION_PROJECTION_INELIGIBLE: "STATICART_EXHIBITION_PROJECTION_INELIGIBLE",

  STATICART_ENTITLEMENT_BLOCKED: "STATICART_ENTITLEMENT_BLOCKED",
  STATICART_SAMPLE_NOT_AVAILABLE: "STATICART_SAMPLE_NOT_AVAILABLE",
  STATICART_ACCESS_NOT_GRANTED: "STATICART_ACCESS_NOT_GRANTED",

  STATICART_STORAGE_UPLOAD_FAILED: "STATICART_STORAGE_UPLOAD_FAILED",
  STATICART_EXTERNAL_PAYMENT_SYNC_FAILED: "STATICART_EXTERNAL_PAYMENT_SYNC_FAILED",
  STATICART_EXTERNAL_SUBSCRIPTION_SYNC_FAILED: "STATICART_EXTERNAL_SUBSCRIPTION_SYNC_FAILED",
  STATICART_RATE_LIMITED: "STATICART_RATE_LIMITED",
  STATICART_INTERNAL_ERROR: "STATICART_INTERNAL_ERROR",
} as const;

export type StaticArtErrorCode =
  typeof STATICART_ERROR_CODES[keyof typeof STATICART_ERROR_CODES];
